Repository WSUCEG-7140/Team-Rainbow--Quiz-Game-App, pull requests merged in 2023-07, with the labels that each got.

#56 Close issue30
  quiz-game/src/Components/SignOut.jsx
Labels: enhancement

#57 Close issue#53
  quiz-game/src/Components/Faculty/ResultGraph.jsx
Labels: enhancement

#62 Added disable quiz functionality in admin Portal
  quiz-game/src/Components/Faculty/FacultyHome.jsx
Labels: enhancement

#60 Closes issue #31
  quiz-game/src/App.jsx
  quiz-game/src/Components/SignUp.jsx
  quiz-game/src/constants/routes.jsx
Labels: good first issue

#59 Created authorization for account
  quiz-game/src/App.jsx
  quiz-game/src/Components/Account.jsx
  quiz-game/src/constants/routes.jsx
Labels: documentation

#69 Close issue#18
  quiz-game/src/Components/Faculty/FacultyHome.jsx
Labels: enhancement

#70 Display error message
  quiz-game/src/App.jsx
  quiz-game/src/Components/E404.jsx
Labels: enhancement

#75 commit to issue#22
  quiz-game/src/Components/Faculty/EditQuiz.jsx
Labels: enhancement

#74 Added new quiz
  quiz-game/src/App.jsx
  quiz-game/src/Components/Faculty/AddQuiz.jsx
  quiz-game/src/constants/routes.jsx
Labels: enhancement

#76 Added styles for error message
  quiz-game/src/Components/E404.css
Labels: good first issue

#77 commit issue 71
  quiz-game/src/Components/Faculty/EditQuiz.jsx
Labels: enhancement

#81 Issue#78
  quiz-game/src/Components/Footer.jsx
Labels: enhancement

#86 Issue#17
  quiz-game/src/Components/Faculty/EditQuiz.jsx
Labels: enhancement

#87 Issue#85
  quiz-game/src/Components/Faculty/EditQuiz.jsx
  quiz-game/src/Components/Footer.test.jsx
Labels: enhancement

#91 Added testing for add_quiz
  quiz-game/src/Components/_tests_/AddQuiz.test.jsx
Labels: Testing

#90 Close issue#89
  quiz-game/src/Components/E404.test.jsx
Labels: Testing

#95 unitest for firebase
  quiz-game/src/Account.jsx
  quiz-game/src/App.jsx
  quiz-game/src/Components/Account.jsx
  quiz-game/src/Components/AuthUserContext.jsx
  quiz-game/src/Components/E404.css
  quiz-game/src/Components/E404.jsx
  quiz-game/src/Components/Faculty/FacultyHome.jsx
  quiz-game/src/Components/Navbar.jsx
  quiz-game/src/Components/PasswordChange.jsx
  quiz-game/src/Components/PasswordForget.jsx
  quiz-game/src/Components/SignIn.jsx
  quiz-game/src/Components/SignOut.jsx
  quiz-game/src/Components/Student/Home.css
  quiz-game/src/Components/Student/Home.jsx
  quiz-game/src/Components/Student/Quiz.css
  quiz-game/src/Components/withAuthentication.jsx
  quiz-game/src/Components/withAuthorization.jsx
  quiz-game/src/TestUtil.jsx
  quiz-game/src/firebase/auth.test.jsx
  quiz-game/src/firebase/db.jsx
  quiz-game/src/firebase/db.test.jsx
  quiz-game/src/firebase/firebase.test.jsx
  quiz-game/src/firebase/index.test.jsx
  quiz-game/src/main.jsx
Labels: Testing

#98 testing for signup
  quiz-game/src/Components/SignUp.test.jsx
Labels: documentation

#97 unit testing for signin
  quiz-game/package-lock.json
  quiz-game/package.json
  quiz-game/src/Components/SignIn.test.jsx
  quiz-game/yarn.lock
Labels: documentation
